spring.application.name=JobForge
jobforge.worker.pollDelayMs=1000

# DataSource
spring.datasource.url=jdbc::postgresql://localhost:5432/jobforge
spring.datasource.username=jobforge
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false